###--Auth
POST {{URL}}/auth/login
Content-Type: application/json

< {{PAYLOAD}}

###
POST {{URL}}/auth/register
Content-Type: application/json

{
  "email": "ageev75@gmail.com",
  "password": "123456"
}

###--USERS
GET {{URL}}/users
Accept: application/json

###
GET {{URL}}/users/profile
Accept: application/json
Authorization: Bearer {{TOKEN}}

###

GET {{URL}}/mail
# Accept: application/json


### --Send Reset Password Link

GET {{URL}}/auth/reset-password-link?email=ageev75@gmail.com
Content-Type: application/json

###

### --Confirm
GET {{URL}}/auth/confirm?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJlbWFpbCI6ImFnZWV2NzVAZ21haWwuY29tIiwibmFtZSI6ImFnZWV2NzVAZ21haWwuY29tIn0sImlhdCI6MTcwNDQ0MDI5NiwiZXhwIjoxNzA0NDQzODk2fQ.K-wh4GTN0gqOlf6n8RyXM8nktzsuAVNrVAiTW0UUsgM
Content-Type: application/json

###

PUT {{URL}}/users/profile
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###
