###-Create course
POST {{URL}}
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###--Get All courses
GET {{URL}}
Accept: application/json


###--Get By Id
GET {{URL}}/6
Accept: application/json

###--Get By Slug
GET {{URL}}/by-slug/learn-adobe-xd-prototyping
Accept: application/json

###--Get Similar
GET {{URL}}/similar/1
Accept: application/json



###---Update course
PUT {{URL}}/1
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

< {{PAYLOAD}}

###---Update views
PATCH {{URL}}/update-views/2
Content-Type: application/json

###---Delete course
DELETE {{URL}}/1
Accept: application/json
Authorization: Bearer {{TOKEN}}
