###-Create category
POST {{URL}}/categories
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###--Get All categories
GET {{URL}}/categories
Accept: application/json

###--Get By Id
GET {{URL}}/categories/1
Accept: application/json

###--Get By Slug
GET {{URL}}/categories/by-slug/design
Accept: application/json


###---Update category
PUT {{URL}}/categories/6
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

< {{PAYLOAD_CATEGORY}}

###---Delete category
DELETE {{URL}}/categories/1
Accept: application/json
Authorization: Bearer {{TOKEN}}
